#!/usr/bin/bash

app=${1:?}

launcher=$(</proc/$PPID/comm)
appname=${app##*/}

if [[ -n "$FUZZEL_DESKTOP_FILE_ID" ]]; then
    appname=${FUZZEL_DESKTOP_FILE_ID%.desktop}
fi

unit_name=app-"$launcher"-"$appname"-$RANDOM

mapfile -d '' </proc/self/environ

run_args=(
    --user
    --same-dir
    --unit="$unit_name"
    --slice=app.slice
    --collect
    -p SuccessExitStatus=130
    -p ExitType=cgroup
    -p SyslogLevel=debug
)

if [[ $XDG_CURRENT_DESKTOP == labwc* ]]; then
    run_args+=(-p EnvironmentFile="$HOME"/.config/labwc/environment)
else
    run_args+=("${MAPFILE[@]/#/--setenv=}")
fi

exec systemd-run "${run_args[@]}" -- "$@"
