#!/usr/bin/bash

app=${1:?}

launcher=$(</proc/$PPID/comm)
appname=${app##*/}

if [[ -n "$FUZZEL_DESKTOP_FILE_ID" ]]; then
    appname=${FUZZEL_DESKTOP_FILE_ID%.desktop}
fi

unit_name=app-"$launcher"-"$appname"-$RANDOM

mapfile -d '' </proc/self/environ

run_args=(
    --user
    --unit="$unit_name"
    --slice=app.slice
    --collect
    -p SuccessExitStatus=130
    -p ExitType=cgroup
    -p SyslogLevel=debug
)

exec systemd-run "${run_args[@]}" "${MAPFILE[@]/#/--setenv=}" -- "$@"
