#!/usr/bin/env python

import os
import sys


def callback(event: bytes):
    for e in event.splitlines():
        if e.startswith(b'workspace>>'):
            sys.stdout.buffer.write(e[11:] + b'\n')
            sys.stdout.flush()


if __name__ == '__main__':
    sys.path.append(os.path.dirname(os.path.abspath(__file__)))
    import hyprland

    with hyprland.socket2() as sock:
        event: bytes = b'workspace>>1\n'
        while True:
            callback(event)
            event = sock.recv(1024)
            if len(event) == 0:
                exit(1)
