#!/usr/bin/env python

import datetime
import sys
import time

if __name__ == '__main__':
    while True:
        s = datetime.datetime.now().strftime("%m-%d %a %T")
        sys.stdout.write(s + '\n')
        sys.stdout.flush()
        time.sleep(1)
