#!/usr/bin/env python

import os
import sys

if __name__ == '__main__':
    sys.path.append(os.path.dirname(os.path.abspath(__file__)))
    import hyprland

    with hyprland.socket2() as sock:
        event: bytes = b'workspace>>1\n'
        while True:
            if event.startswith(b'workspace>>'):
                sys.stdout.buffer.write(event[11:])
                sys.stdout.flush()
            event = sock.recv(1024)
            if len(event) == 0:
                exit(1)
