# "$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '$all'
right_format = '$time'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red) '

[directory]
style = 'bold underline cyan'
truncation_symbol = '…/'

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = '%T%Z'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)](green)'
renamed = 'renamed'
